-- Utah sample venues for local / staging data.
--
-- Columns below are exactly those read by the iOS app for Discover / Following
-- (`discoverVenueRowSelectColumns` in MapViewModel+VenueAndGameData.swift and
-- `venueSelectColumnsFollowing` in MapViewModel+FollowingTab.swift), matching
-- VenueProfileRow / VenueRow in MapViewModelTypes.swift.
--
-- Additional `public.venues` columns from repo migrations (not inserted here;
-- they use database defaults or remain NULL):
--   - cover_photo_thumbnail_url, menu_photo_thumbnail_url
--       (added 20260513_0001_image_thumbnail_columns.sql)
--   - admin_status NOT NULL DEFAULT 'active',
--     admin_archived_at, admin_archived_by, admin_archived_reason
--       (added 20260519_0001_admin_lifecycle_audit_logging.sql)
--
-- No CREATE TABLE for `venues` exists in this repository’s migrations; do not
-- add columns here unless they appear in the sources above or a migration.

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000001'::uuid,
  'seed.utah.beerhive@example.test',
  'Beerhive Pub',
  '128 S Main St',
  'Salt Lake City',
  'UT',
  '84101',
  '8015550101',
  '',
  'Downtown Salt Lake sports bar with multiple screens.',
  'Downtown,Main Street',
  12,
  true,
  true,
  false,
  true,
  false,
  40.7669,
  -111.8910,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.beerhive@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000002'::uuid,
  'seed.utah.legends@example.test',
  'Legends Sports Pub',
  '677 S 200 W',
  'Salt Lake City',
  'UT',
  '84101',
  '8015550102',
  '',
  'Soccer and football friendly pub near Vivint area.',
  'Soccer,Big screens',
  8,
  true,
  true,
  false,
  false,
  true,
  40.7590,
  -111.9010,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.legends@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000003'::uuid,
  'seed.utah.provo-row@example.test',
  'The Pitch Provo',
  '4801 N University Ave',
  'Provo',
  'UT',
  '84604',
  '8015550103',
  '',
  'College town sports spot with outdoor patio TVs.',
  'College town,Patio',
  6,
  true,
  true,
  true,
  false,
  false,
  40.2971,
  -111.6595,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.provo-row@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000004'::uuid,
  'seed.utah.ogden-union@example.test',
  'Union Grill & Sports',
  '2501 Wall Ave',
  'Ogden',
  'UT',
  '84401',
  '8015550104',
  '',
  'Ogden mainline sports viewing and food specials.',
  'Ogden,Family friendly',
  10,
  true,
  true,
  false,
  true,
  false,
  41.2230,
  -111.9738,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.ogden-union@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000005'::uuid,
  'seed.utah.stgeorge-red@example.test',
  'Red Rock Tavern',
  '25 N Main St',
  'St. George',
  'UT',
  '84770',
  '4355550105',
  '',
  'Southern Utah spot for NBA and MLS nights.',
  'Southern Utah,Downtown',
  9,
  true,
  true,
  false,
  true,
  true,
  37.0965,
  -113.5684,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.stgeorge-red@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000006'::uuid,
  'seed.utah.moab-rim@example.test',
  'Rimrock Sports Bar',
  '58 S Main St',
  'Moab',
  'UT',
  '84532',
  '4355550106',
  '',
  'Moab downtown bar with game-day specials.',
  'Moab,Tourism',
  4,
  true,
  true,
  false,
  false,
  false,
  38.5723,
  -109.5498,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.moab-rim@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000007'::uuid,
  'seed.utah.logan-cache@example.test',
  'Cache Valley Sports Lounge',
  '696 N Main St',
  'Logan',
  'UT',
  '84321',
  '4355550107',
  '',
  'Logan USU-area sports lounge.',
  'Logan,College',
  7,
  true,
  true,
  false,
  false,
  false,
  41.7363,
  -111.8358,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.logan-cache@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000008'::uuid,
  'seed.utah.parkcity-alpine@example.test',
  'Alpine View Tavern',
  '738 Lower Main St',
  'Park City',
  'UT',
  '84060',
  '4355550108',
  '',
  'Park City Main Street sports viewing.',
  'Park City,Resort',
  5,
  true,
  true,
  false,
  false,
  true,
  40.6412,
  -111.4965,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.parkcity-alpine@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000009'::uuid,
  'seed.utah.sandy-state@example.test',
  'State Street Tavern',
  '10600 S State St',
  'Sandy',
  'UT',
  '84070',
  '8015550109',
  '',
  'South Valley neighborhood pub with game-day screens.',
  'Sandy,South Valley',
  10,
  true,
  true,
  false,
  true,
  false,
  40.5657,
  -111.8902,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.sandy-state@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000010'::uuid,
  'seed.utah.draper-traverse@example.test',
  'Traverse Ridge Grill',
  '13800 S Bangerter Hwy',
  'Draper',
  'UT',
  '84020',
  '8015550110',
  '',
  'Draper bench-area grill and sports viewing.',
  'Draper,Bangerter',
  8,
  true,
  true,
  false,
  false,
  false,
  40.5247,
  -111.8588,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.draper-traverse@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000011'::uuid,
  'seed.utah.southjordan-sojo@example.test',
  'SoJo Social House',
  '11259 S Kestrel Rise Rd',
  'South Jordan',
  'UT',
  '84095',
  '8015550111',
  '',
  'South Jordan gathering spot for games and food.',
  'South Jordan,Daybreak',
  6,
  true,
  true,
  false,
  false,
  true,
  40.9142,
  -111.9806,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.southjordan-sojo@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000012'::uuid,
  'seed.utah.westjordan-landing@example.test',
  'Jordan Landing Pub',
  '7182 S Plaza Center Dr',
  'West Jordan',
  'UT',
  '84084',
  '8015550112',
  '',
  'West Jordan plaza-area pub with TVs for sports.',
  'West Jordan,Jordan Landing',
  9,
  true,
  true,
  false,
  true,
  false,
  40.6097,
  -111.9391,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.westjordan-landing@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000013'::uuid,
  'seed.utah.orem-parkway@example.test',
  'University Parkway Tavern',
  '765 E University Pkwy',
  'Orem',
  'UT',
  '84097',
  '8015550113',
  '',
  'Orem university-corridor tavern for game nights.',
  'Orem,University Parkway',
  7,
  true,
  true,
  false,
  false,
  false,
  40.2969,
  -111.6946,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.orem-parkway@example.test'
);

INSERT INTO public.venues (
  id,
  owner_email,
  venue_name,
  address,
  city,
  state,
  zip_code,
  phone,
  website,
  description,
  features,
  screen_count,
  serves_food,
  has_wifi,
  has_garden,
  has_projector,
  pet_friendly,
  latitude,
  longitude,
  cover_photo_url,
  menu_photo_url,
  cover_photo_thumbnail_url,
  menu_photo_thumbnail_url
)
SELECT
  'a1000001-0001-4001-8001-000000000014'::uuid,
  'seed.utah.cedar-main@example.test',
  'Main Street Social Cedar',
  '86 N Main St',
  'Cedar City',
  'UT',
  '84720',
  '4355550114',
  '',
  'Cedar City downtown social house with sports TVs.',
  'Cedar City,Downtown',
  5,
  true,
  true,
  false,
  false,
  true,
  37.6775,
  -113.0619,
  '',
  '',
  NULL,
  NULL
WHERE NOT EXISTS (
  SELECT 1 FROM public.venues v WHERE v.owner_email = 'seed.utah.cedar-main@example.test'
);
