export const FAVORITE_TEAM_MATCH_ALIASES: Record<string, string[]> = {
  "badminton-an-se-young": ["an se young"],
  "badminton-carolina-marin": ["carolina marin"],
  "badminton-lee-zii-jia": ["lee zii jia"],
  "badminton-pv-sindhu": ["p v sindhu"],
  "badminton-tai-tzu-ying": ["tai tzu ying"],
  "badminton-thomas-cup": ["thomas cup"],
  "badminton-uber-cup": ["uber cup"],
  "badminton-viktor-axelsen": ["viktor axelsen"],
  "badminton-world-championships": ["bwf world championships"],
  "dance-ballet": ["ballet"],
  "dance-break-dance": ["break dance"],
  "driver-charles-leclerc": ["charles leclerc"],
  "driver-lando-norris": ["lando norris"],
  "driver-lewis-hamilton": ["lewis hamilton"],
  "driver-max-verstappen": ["max verstappen"],
  "f1-american-racing": ["american racing"],
  "f1-australian-racing": ["australian racing"],
  "f1-austrian-racing": ["austrian racing"],
  "f1-brazilian-racing": ["brazilian racing"],
  "f1-british-racing": ["british racing"],
  "f1-dutch-racing": ["dutch racing"],
  "f1-french-racing": ["french racing"],
  "f1-german-racing": ["german racing"],
  "f1-italian-racing": ["italian racing"],
  "f1-japanese-racing": ["japanese racing"],
  "f1-monaco-racing": ["monaco racing"],
  "f1-spanish-racing": ["spanish racing"],
  "fighter-alex-pereira": ["alex pereira"],
  "fighter-amanda-nunes": ["amanda nunes"],
  "fighter-claressa-shields": ["claressa shields"],
  "fighter-islam-makhachev": ["islam makhachev"],
  "fighter-jon-jones": ["jon jones"],
  "fighter-katie-taylor": ["katie taylor"],
  "golf-lydia-ko": ["lydia ko"],
  "golf-masters": ["the masters"],
  "golf-nelly-korda": ["nelly korda"],
  "golf-rory-mcilroy": ["rory mcilroy"],
  "golf-ryder-cup": ["ryder cup"],
  "golf-scottie-scheffler": ["scottie scheffler"],
  "golf-the-open": ["the open"],
  "golf-tiger-woods": ["tiger woods"],
  "golf-us-open": ["u s open golf"],
  "league-formula-one": ["formula 1"],
  "league-mlb": ["mlb"],
  "league-mls": ["mls"],
  "league-nba": ["nba"],
  "league-nfl": ["nfl"],
  "league-premier-league": ["premier league"],
  "mlb-astros": ["houston astros"],
  "mlb-braves": ["atlanta braves"],
  "mlb-cardinals": ["st louis cardinals"],
  "mlb-cubs": ["chicago cubs"],
  "mlb-dodgers": ["los angeles dodgers"],
  "mlb-giants": ["san francisco giants"],
  "mlb-mariners": ["seattle mariners"],
  "mlb-mets": ["new york mets"],
  "mlb-padres": ["san diego padres"],
  "mlb-phillies": ["philadelphia phillies"],
  "mlb-red-sox": ["boston red sox"],
  "mlb-yankees": ["new york yankees"],
  "nba-bucks": ["milwaukee bucks"],
  "nba-bulls": ["chicago bulls"],
  "nba-celtics": ["boston celtics"],
  "nba-heat": ["miami heat"],
  "nba-knicks": ["new york knicks"],
  "nba-lakers": ["los angeles lakers"],
  "nba-mavericks": ["dallas mavericks"],
  "nba-nets": ["brooklyn nets"],
  "nba-nuggets": ["denver nuggets"],
  "nba-spurs": ["san antonio spurs"],
  "nba-suns": ["phoenix suns"],
  "nba-warriors": ["golden state warriors"],
  "ncaa-alabama-cfb": ["alabama college football"],
  "ncaa-duke-cbb": ["durham college basketball"],
  "ncaa-georgia-cfb": ["georgia college football"],
  "ncaa-gonzaga-cbb": ["spokane college basketball"],
  "ncaa-kansas-cbb": ["kansas college basketball"],
  "ncaa-kentucky-cbb": ["kentucky college basketball"],
  "ncaa-la-cbb": ["los angeles college basketball"],
  "ncaa-michigan-cfb": ["michigan college football"],
  "ncaa-ohio-cfb": ["ohio college football"],
  "ncaa-oregon-cfb": ["oregon college football"],
  "ncaa-texas-cfb": ["texas college football"],
  "ncaa-utah-cfb": ["utah college football"],
  "nfl-49ers": ["san francisco 49ers"],
  "nfl-bengals": ["cincinnati bengals"],
  "nfl-bills": ["buffalo bills"],
  "nfl-chiefs": ["kansas city chiefs"],
  "nfl-cowboys": ["dallas cowboys"],
  "nfl-dolphins": ["miami dolphins"],
  "nfl-eagles": ["philadelphia eagles"],
  "nfl-jets": ["new york jets"],
  "nfl-lions": ["detroit lions"],
  "nfl-packers": ["green bay packers"],
  "nfl-ravens": ["baltimore ravens"],
  "nfl-steelers": ["pittsburgh steelers"],
  "nhl-boston-hockey": ["boston hockey"],
  "nhl-chicago-hockey": ["chicago hockey"],
  "nhl-colorado-hockey": ["colorado hockey"],
  "nhl-dallas-hockey": ["dallas hockey"],
  "nhl-detroit-hockey": ["detroit hockey"],
  "nhl-edmonton-hockey": ["edmonton hockey"],
  "nhl-montreal-hockey": ["montreal hockey"],
  "nhl-pittsburgh-hockey": ["pittsburgh hockey"],
  "nhl-seattle-hockey": ["seattle hockey"],
  "nhl-tampa-hockey": ["tampa hockey"],
  "nhl-toronto-hockey": ["toronto hockey"],
  "nhl-vegas-hockey": ["vegas hockey"],
  "player-caitlin-clark": ["caitlin clark"],
  "player-cristiano-ronaldo": ["cristiano ronaldo"],
  "player-kylian-mbappe": ["kylian mbappe"],
  "player-lebron-james": ["lebron james"],
  "player-lionel-messi": ["lionel messi"],
  "player-patrick-mahomes": ["patrick mahomes"],
  "player-shohei-ohtani": ["shohei ohtani"],
  "player-stephen-curry": ["stephen curry"],
  "soccer-ajax": ["ajax"],
  "soccer-argentina": ["argentina"],
  "soccer-arsenal": ["arsenal"],
  "soccer-atlanta": ["atlanta united"],
  "soccer-atletico-madrid": ["atl tico madrid"],
  "soccer-australia": ["australia"],
  "soccer-barcelona": ["barcelona"],
  "soccer-bayern": ["bayern munich"],
  "soccer-benfica": ["benfica"],
  "soccer-brazil": ["brazil"],
  "soccer-canada": ["canada"],
  "soccer-cf-montreal": ["cf montr al"],
  "soccer-chelsea": ["chelsea"],
  "soccer-chivas": ["chivas"],
  "soccer-club-america": ["club am rica"],
  "soccer-dortmund": ["borussia dortmund"],
  "soccer-england": ["england"],
  "soccer-france": ["france"],
  "soccer-galaxy": ["la galaxy"],
  "soccer-germany": ["germany"],
  "soccer-inter": ["inter milan"],
  "soccer-inter-miami": ["inter miami"],
  "soccer-italy": ["italy"],
  "soccer-japan": ["japan"],
  "soccer-juventus": ["juventus"],
  "soccer-lafc": ["lafc"],
  "soccer-liverpool": ["liverpool"],
  "soccer-man-city": ["manchester city"],
  "soccer-man-utd": ["manchester united"],
  "soccer-marseille": ["marseille"],
  "soccer-mexico": ["mexico"],
  "soccer-milan": ["ac milan"],
  "soccer-monterrey": ["monterrey"],
  "soccer-morocco": ["morocco"],
  "soccer-napoli": ["napoli"],
  "soccer-netherlands": ["netherlands"],
  "soccer-nycfc": ["new york city fc"],
  "soccer-porto": ["porto"],
  "soccer-portugal": ["portugal"],
  "soccer-psg": ["paris saint germain"],
  "soccer-pumas": ["pumas"],
  "soccer-real-madrid": ["real madrid"],
  "soccer-roma": ["roma"],
  "soccer-seattle": ["seattle sounders"],
  "soccer-south-korea": ["south korea"],
  "soccer-spain": ["spain"],
  "soccer-tigres": ["tigres"],
  "soccer-toronto": ["toronto fc"],
  "soccer-tottenham": ["tottenham"],
  "soccer-usa": ["united states"],
  "tennis-aryna-sabalenka": ["aryna sabalenka"],
  "tennis-australian-open": ["australian open"],
  "tennis-carlos-alcaraz": ["carlos alcaraz"],
  "tennis-coco-gauff": ["coco gauff"],
  "tennis-iga-swiatek": ["iga swiatek"],
  "tennis-jannik-sinner": ["jannik sinner"],
  "tennis-naomi-osaka": ["naomi osaka"],
  "tennis-novak-djokovic": ["novak djokovic"],
  "tennis-rafael-nadal": ["rafael nadal"],
  "tennis-roland-garros": ["roland garros"],
  "tennis-serena-williams": ["serena williams"],
  "tennis-us-open": ["us open tennis"],
  "tennis-wimbledon": ["wimbledon"],
  "tournament-champions-league": ["champions league"],
  "tournament-college-football-playoff": ["college football playoff"],
  "tournament-march-madness": ["march madness"],
  "tournament-world-cup": ["fifa world cup"],
};