#!/usr/bin/env python3
"""Localization for Owner-grantable Team permissions (Player Information)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XCSTRINGS = ROOT / "GameOn" / "Localizable.xcstrings"
SUPPORTED = ["en", "es", "fr", "pt", "de", "it", "pl", "ru", "sq", "zh-Hans", "nl"]


def unit(value: str) -> dict:
    return {"stringUnit": {"state": "translated", "value": value}}


def locs(translations: dict[str, str]) -> dict:
    return {lang: unit(translations[lang]) for lang in SUPPORTED if lang in translations}


ENTRIES: dict[str, dict[str, str]] = {
    "fan_team_permissions_section": {
        "en": "Permissions",
        "es": "Permisos",
        "fr": "Autorisations",
        "pt": "Permissões",
        "de": "Berechtigungen",
        "it": "Autorizzazioni",
        "nl": "Rechten",
        "pl": "Uprawnienia",
        "ru": "Права",
        "sq": "Lejet",
        "zh-Hans": "权限",
    },
    "fan_team_permission_create_events_title": {
        "en": "Can create events",
        "es": "Puede crear eventos",
        "fr": "Peut créer des événements",
        "pt": "Pode criar eventos",
        "de": "Kann Events erstellen",
        "it": "Può creare eventi",
        "nl": "Kan evenementen maken",
        "pl": "Może tworzyć wydarzenia",
        "ru": "Может создавать события",
        "sq": "Mund të krijojë ngjarje",
        "zh-Hans": "可创建活动",
    },
    "fan_team_permission_create_events_help": {
        "en": "Allows this member to create Team practices, games and meetings.",
        "es": "Permite a este miembro crear prácticas, partidos y reuniones del equipo.",
        "fr": "Permet à ce membre de créer des entraînements, matchs et réunions d’équipe.",
        "pt": "Permite a este membro criar treinos, jogos e reuniões da equipe.",
        "de": "Erlaubt diesem Mitglied, Team-Trainings, Spiele und Meetings zu erstellen.",
        "it": "Consente a questo membro di creare allenamenti, partite e riunioni di squadra.",
        "nl": "Laat dit lid Teamtrainingen, wedstrijden en meetings maken.",
        "pl": "Pozwala temu członkowi tworzyć treningi, mecze i spotkania drużyny.",
        "ru": "Позволяет участнику создавать тренировки, игры и встречи команды.",
        "sq": "Lejon këtë anëtar të krijojë stërvitje, ndeshje dhe takime ekipi.",
        "zh-Hans": "允许该成员创建队伍的训练、比赛和会议。",
    },
    "fan_team_permission_edit_events_title": {
        "en": "Can edit events",
        "es": "Puede editar eventos",
        "fr": "Peut modifier des événements",
        "pt": "Pode editar eventos",
        "de": "Kann Events bearbeiten",
        "it": "Può modificare eventi",
        "nl": "Kan evenementen bewerken",
        "pl": "Może edytować wydarzenia",
        "ru": "Может редактировать события",
        "sq": "Mund të ndryshojë ngjarje",
        "zh-Hans": "可编辑活动",
    },
    "fan_team_permission_edit_events_help": {
        "en": "Allows this member to edit existing Team practices, games and meetings.",
        "es": "Permite a este miembro editar prácticas, partidos y reuniones existentes.",
        "fr": "Permet à ce membre de modifier les entraînements, matchs et réunions existants.",
        "pt": "Permite a este membro editar treinos, jogos e reuniões existentes.",
        "de": "Erlaubt diesem Mitglied, bestehende Team-Events zu bearbeiten.",
        "it": "Consente a questo membro di modificare eventi di squadra esistenti.",
        "nl": "Laat dit lid bestaande Teamevenementen bewerken.",
        "pl": "Pozwala temu członkowi edytować istniejące wydarzenia drużyny.",
        "ru": "Позволяет участнику редактировать существующие события команды.",
        "sq": "Lejon këtë anëtar të ndryshojë ngjarjet ekzistuese të ekipit.",
        "zh-Hans": "允许该成员编辑已有的队伍活动。",
    },
    "fan_team_permission_publish_announcements_title": {
        "en": "Can publish announcements",
        "es": "Puede publicar anuncios",
        "fr": "Peut publier des annonces",
        "pt": "Pode publicar avisos",
        "de": "Kann Ankündigungen veröffentlichen",
        "it": "Può pubblicare annunci",
        "nl": "Kan aankondigingen publiceren",
        "pl": "Może publikować ogłoszenia",
        "ru": "Может публиковать объявления",
        "sq": "Mund të publikojë njoftime",
        "zh-Hans": "可发布公告",
    },
    "fan_team_permission_publish_announcements_help": {
        "en": "Allows this member to post Team Announcements for the whole Team.",
        "es": "Permite a este miembro publicar anuncios del equipo para todos.",
        "fr": "Permet à ce membre de publier des annonces d’équipe pour toute l’équipe.",
        "pt": "Permite a este membro publicar avisos da equipe para todos.",
        "de": "Erlaubt diesem Mitglied, Team-Ankündigungen für das ganze Team zu posten.",
        "it": "Consente a questo membro di pubblicare annunci di squadra.",
        "nl": "Laat dit lid Teamaankondigingen voor het hele team plaatsen.",
        "pl": "Pozwala temu członkowi publikować ogłoszenia dla całej drużyny.",
        "ru": "Позволяет участнику публиковать объявления для всей команды.",
        "sq": "Lejon këtë anëtar të publikojë njoftime për të gjithë ekipin.",
        "zh-Hans": "允许该成员向全队发布队伍公告。",
    },
    "fan_team_permission_invite_members_title": {
        "en": "Can invite members",
        "es": "Puede invitar miembros",
        "fr": "Peut inviter des membres",
        "pt": "Pode convidar membros",
        "de": "Kann Mitglieder einladen",
        "it": "Può invitare membri",
        "nl": "Kan leden uitnodigen",
        "pl": "Może zapraszać członków",
        "ru": "Может приглашать участников",
        "sq": "Mund të ftojë anëtarë",
        "zh-Hans": "可邀请成员",
    },
    "fan_team_permission_invite_members_help": {
        "en": "Allows this member to invite people to join the Team.",
        "es": "Permite a este miembro invitar personas a unirse al equipo.",
        "fr": "Permet à ce membre d’inviter des personnes à rejoindre l’équipe.",
        "pt": "Permite a este membro convidar pessoas para a equipe.",
        "de": "Erlaubt diesem Mitglied, Personen zum Team einzuladen.",
        "it": "Consente a questo membro di invitare persone nella squadra.",
        "nl": "Laat dit lid mensen uitnodigen voor het Team.",
        "pl": "Pozwala temu członkowi zapraszać osoby do drużyny.",
        "ru": "Позволяет участнику приглашать людей в команду.",
        "sq": "Lejon këtë anëtar të ftojë njerëz në ekip.",
        "zh-Hans": "允许该成员邀请他人加入队伍。",
    },
    "fan_team_permission_manage_roster_title": {
        "en": "Can manage roster",
        "es": "Puede gestionar la plantilla",
        "fr": "Peut gérer l’effectif",
        "pt": "Pode gerenciar o elenco",
        "de": "Kann den Kader verwalten",
        "it": "Può gestire la rosa",
        "nl": "Kan de selectie beheren",
        "pl": "Może zarządzać składem",
        "ru": "Может управлять составом",
        "sq": "Mund të menaxhojë listën",
        "zh-Hans": "可管理名单",
    },
    "fan_team_permission_manage_roster_help": {
        "en": "Allows this member to manage Team roster details such as jersey numbers.",
        "es": "Permite gestionar detalles de la plantilla, como números de dorsal.",
        "fr": "Permet de gérer les détails de l’effectif, comme les numéros de maillot.",
        "pt": "Permite gerenciar detalhes do elenco, como números de camisa.",
        "de": "Erlaubt die Verwaltung von Kaderdetails wie Trikotnummern.",
        "it": "Consente di gestire dettagli della rosa come i numeri di maglia.",
        "nl": "Laat selectiedetails zoals shirtnummers beheren.",
        "pl": "Pozwala zarządzać szczegółami składu, np. numerami koszulek.",
        "ru": "Позволяет управлять данными состава, например номерами.",
        "sq": "Lejon menaxhimin e detajeve të listës, si numrat e fanellës.",
        "zh-Hans": "允许管理名单细节（如球衣号码）。",
    },
    "fan_team_permission_manage_lineups_title": {
        "en": "Can manage lineups",
        "es": "Puede gestionar alineaciones",
        "fr": "Peut gérer les compositions",
        "pt": "Pode gerenciar escalações",
        "de": "Kann Aufstellungen verwalten",
        "it": "Può gestire le formazioni",
        "nl": "Kan opstellingen beheren",
        "pl": "Może zarządzać składami meczowymi",
        "ru": "Может управлять составами на матч",
        "sq": "Mund të menaxhojë formacionet",
        "zh-Hans": "可管理阵容",
    },
    "fan_team_permission_manage_lineups_help": {
        "en": "Allows this member to create and edit event lineups.",
        "es": "Permite crear y editar alineaciones de eventos.",
        "fr": "Permet de créer et modifier les compositions d’événements.",
        "pt": "Permite criar e editar escalações de eventos.",
        "de": "Erlaubt das Erstellen und Bearbeiten von Event-Aufstellungen.",
        "it": "Consente di creare e modificare le formazioni degli eventi.",
        "nl": "Laat eventopstellingen maken en bewerken.",
        "pl": "Pozwala tworzyć i edytować składy wydarzeń.",
        "ru": "Позволяет создавать и редактировать составы на события.",
        "sq": "Lejon krijimin dhe ndryshimin e formacioneve të ngjarjeve.",
        "zh-Hans": "允许创建和编辑活动阵容。",
    },
    "fan_team_permission_manage_managed_players_title": {
        "en": "Can manage managed players",
        "es": "Puede gestionar jugadores tutelados",
        "fr": "Peut gérer les joueurs gérés",
        "pt": "Pode gerenciar jogadores tutelados",
        "de": "Kann betreute Spieler verwalten",
        "it": "Può gestire i giocatori gestiti",
        "nl": "Kan beheerde spelers beheren",
        "pl": "Może zarządzać podopiecznymi",
        "ru": "Может управлять подопечными игроками",
        "sq": "Mund të menaxhojë lojtarët e menaxhuar",
        "zh-Hans": "可管理托管球员",
    },
    "fan_team_permission_manage_managed_players_help": {
        "en": "Allows this member to add or manage guardian-managed players on the Team.",
        "es": "Permite añadir o gestionar jugadores tutelados en el equipo.",
        "fr": "Permet d’ajouter ou gérer des joueurs sous tutelle dans l’équipe.",
        "pt": "Permite adicionar ou gerenciar jogadores tutelados na equipe.",
        "de": "Erlaubt das Hinzufügen/Verwalten betreuter Spieler im Team.",
        "it": "Consente di aggiungere o gestire giocatori gestiti nella squadra.",
        "nl": "Laat beheerde spelers aan het Team toevoegen of beheren.",
        "pl": "Pozwala dodawać lub zarządzać podopiecznymi w drużynie.",
        "ru": "Позволяет добавлять и управлять подопечными игроками в команде.",
        "sq": "Lejon shtimin ose menaxhimin e lojtarëve të menaxhuar në ekip.",
        "zh-Hans": "允许在队伍中添加或管理托管球员。",
    },
    "fan_team_permission_edit_team_information_title": {
        "en": "Can edit team information",
        "es": "Puede editar la información del equipo",
        "fr": "Peut modifier les informations de l’équipe",
        "pt": "Pode editar informações da equipe",
        "de": "Kann Teaminformationen bearbeiten",
        "it": "Può modificare le informazioni della squadra",
        "nl": "Kan teaminformatie bewerken",
        "pl": "Może edytować informacje o drużynie",
        "ru": "Может редактировать сведения о команде",
        "sq": "Mund të ndryshojë informacionin e ekipit",
        "zh-Hans": "可编辑队伍信息",
    },
    "fan_team_permission_edit_team_information_help": {
        "en": "Allows this member to edit Team name, sport, logo and related details.",
        "es": "Permite editar nombre, deporte, logo y detalles del equipo.",
        "fr": "Permet de modifier le nom, le sport, le logo et les détails de l’équipe.",
        "pt": "Permite editar nome, esporte, logo e detalhes da equipe.",
        "de": "Erlaubt das Bearbeiten von Name, Sport, Logo und Teamdetails.",
        "it": "Consente di modificare nome, sport, logo e dettagli della squadra.",
        "nl": "Laat Teamnaam, sport, logo en details bewerken.",
        "pl": "Pozwala edytować nazwę, sport, logo i szczegóły drużyny.",
        "ru": "Позволяет редактировать название, спорт, логотип и детали команды.",
        "sq": "Lejon ndryshimin e emrit, sportit, logos dhe detajeve të ekipit.",
        "zh-Hans": "允许编辑队伍名称、运动项目、队徽及相关信息。",
    },
    "fan_team_permission_moderate_team_chat_title": {
        "en": "Can moderate Team Chat",
        "es": "Puede moderar el chat del equipo",
        "fr": "Peut modérer le chat d’équipe",
        "pt": "Pode moderar o chat da equipe",
        "de": "Kann den Team-Chat moderieren",
        "it": "Può moderare la chat di squadra",
        "nl": "Kan Teamchat modereren",
        "pl": "Może moderować czat drużyny",
        "ru": "Может модерировать чат команды",
        "sq": "Mund të moderojë bisedën e ekipit",
        "zh-Hans": "可管理队伍聊天",
    },
    "fan_team_permission_moderate_team_chat_help": {
        "en": "Allows this member to moderate messages in Team Chat.",
        "es": "Permite moderar mensajes en el chat del equipo.",
        "fr": "Permet de modérer les messages du chat d’équipe.",
        "pt": "Permite moderar mensagens no chat da equipe.",
        "de": "Erlaubt die Moderation von Nachrichten im Team-Chat.",
        "it": "Consente di moderare i messaggi nella chat di squadra.",
        "nl": "Laat berichten in Teamchat modereren.",
        "pl": "Pozwala moderować wiadomości w czacie drużyny.",
        "ru": "Позволяет модерировать сообщения в чате команды.",
        "sq": "Lejon moderimin e mesazheve në bisedën e ekipit.",
        "zh-Hans": "允许管理队伍聊天中的消息。",
    },
}


def main() -> None:
    data = json.loads(XCSTRINGS.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})
    for key, translations in ENTRIES.items():
        strings[key] = {
            "extractionState": "manual",
            "localizations": locs(translations),
        }
    XCSTRINGS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Patched {len(ENTRIES)} keys into {XCSTRINGS}")


if __name__ == "__main__":
    main()
