#!/usr/bin/env python3
"""Localizations for Pickup progressive creation + Event Type terminology."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XCSTRINGS = ROOT / "GameOn" / "Localizable.xcstrings"
SUPPORTED = ["en", "es", "fr", "pt", "de", "it", "pl", "ru", "sq", "zh-Hans", "nl"]


def unit(value: str) -> dict:
    return {"stringUnit": {"state": "translated", "value": value}}


def locs(translations: dict[str, str]) -> dict:
    return {lang: unit(translations[lang]) for lang in SUPPORTED if lang in translations}


ENTRIES: dict[str, dict[str, str]] = {
    "pickup_form_event_type": {
        "en": "Event type",
        "es": "Tipo de evento",
        "fr": "Type d’événement",
        "pt": "Tipo de evento",
        "de": "Eventtyp",
        "it": "Tipo di evento",
        "pl": "Typ wydarzenia",
        "ru": "Тип события",
        "sq": "Lloji i eventit",
        "zh-Hans": "活动类型",
        "nl": "Evenementtype",
    },
    "pickup_form_event_type_subtitle": {
        "en": "What type of event is this?",
        "es": "¿Qué tipo de evento es?",
        "fr": "Quel type d’événement est-ce ?",
        "pt": "Que tipo de evento é este?",
        "de": "Welche Art von Event ist das?",
        "it": "Che tipo di evento è?",
        "pl": "Jaki to rodzaj wydarzenia?",
        "ru": "Какой это тип события?",
        "sq": "Çfarë lloji eventi është ky?",
        "zh-Hans": "这是什么类型的活动？",
        "nl": "Wat voor evenement is dit?",
    },
    "pickup_form_section_pickup_details": {
        "en": "Pickup Details",
        "es": "Detalles del pickup",
        "fr": "Détails du pickup",
        "pt": "Detalhes do pickup",
        "de": "Pickup-Details",
        "it": "Dettagli pickup",
        "pl": "Szczegóły pickup",
        "ru": "Детали пикапа",
        "sq": "Detajet e pickup",
        "zh-Hans": "约局详情",
        "nl": "Pickup-details",
    },
    "pickup_form_section_participants": {
        "en": "Participants",
        "es": "Participantes",
        "fr": "Participants",
        "pt": "Participantes",
        "de": "Teilnehmer",
        "it": "Partecipanti",
        "pl": "Uczestnicy",
        "ru": "Участники",
        "sq": "Pjesëmarrësit",
        "zh-Hans": "参与者",
        "nl": "Deelnemers",
    },
    "pickup_form_participants_needed": {
        "en": "Participants needed",
        "es": "Participantes necesarios",
        "fr": "Participants nécessaires",
        "pt": "Participantes necessários",
        "de": "Benötigte Teilnehmer",
        "it": "Partecipanti necessari",
        "pl": "Potrzebni uczestnicy",
        "ru": "Нужно участников",
        "sq": "Pjesëmarrës të nevojshëm",
        "zh-Hans": "所需参与者",
        "nl": "Deelnemers nodig",
    },
    "pickup_form_max_participants": {
        "en": "Max participants",
        "es": "Máx. de participantes",
        "fr": "Participants max",
        "pt": "Máx. de participantes",
        "de": "Max. Teilnehmer",
        "it": "Partecipanti max",
        "pl": "Maks. uczestników",
        "ru": "Макс. участников",
        "sq": "Maks. pjesëmarrës",
        "zh-Hans": "参与者上限",
        "nl": "Max. deelnemers",
    },
    "pickup_form_participant_count_one": {
        "en": "1 participant",
        "es": "1 participante",
        "fr": "1 participant",
        "pt": "1 participante",
        "de": "1 Teilnehmer",
        "it": "1 partecipante",
        "pl": "1 uczestnik",
        "ru": "1 участник",
        "sq": "1 pjesëmarrës",
        "zh-Hans": "1 名参与者",
        "nl": "1 deelnemer",
    },
    "pickup_form_participant_count_other_format": {
        "en": "%d participants",
        "es": "%d participantes",
        "fr": "%d participants",
        "pt": "%d participantes",
        "de": "%d Teilnehmer",
        "it": "%d partecipanti",
        "pl": "%d uczestników",
        "ru": "%d участников",
        "sq": "%d pjesëmarrës",
        "zh-Hans": "%d 名参与者",
        "nl": "%d deelnemers",
    },
    "pickup_event_type_match": {
        "en": "Match",
        "es": "Partido",
        "fr": "Match",
        "pt": "Partida",
        "de": "Spiel",
        "it": "Partita",
        "pl": "Mecz",
        "ru": "Матч",
        "sq": "Ndeshje",
        "zh-Hans": "比赛",
        "nl": "Wedstrijd",
    },
    "pickup_event_type_training": {
        "en": "Training",
        "es": "Entrenamiento",
        "fr": "Entraînement",
        "pt": "Treino",
        "de": "Training",
        "it": "Allenamento",
        "pl": "Trening",
        "ru": "Тренировка",
        "sq": "Stërvitje",
        "zh-Hans": "训练",
        "nl": "Training",
    },
    "pickup_event_type_training_workout": {
        "en": "Training / Workout",
        "es": "Entrenamiento / Workout",
        "fr": "Entraînement / Workout",
        "pt": "Treino / Workout",
        "de": "Training / Workout",
        "it": "Allenamento / Workout",
        "pl": "Trening / Workout",
        "ru": "Тренировка / Workout",
        "sq": "Stërvitje / Workout",
        "zh-Hans": "训练 / 锻炼",
        "nl": "Training / Workout",
    },
    "pickup_event_type_group_run": {
        "en": "Group Run / Activity",
        "es": "Carrera / actividad en grupo",
        "fr": "Course / activité de groupe",
        "pt": "Corrida / atividade em grupo",
        "de": "Gruppenlauf / Aktivität",
        "it": "Corsa / attività di gruppo",
        "pl": "Bieg / aktywność grupowa",
        "ru": "Групповой забег / активность",
        "sq": "Vrapim / aktivitet në grup",
        "zh-Hans": "团跑 / 团体活动",
        "nl": "Groepsrun / activiteit",
    },
    "pickup_event_type_group_ride": {
        "en": "Group Ride / Activity",
        "es": "Salida / actividad en grupo",
        "fr": "Sortie / activité de groupe",
        "pt": "Pedalada / atividade em grupo",
        "de": "Gruppenfahrt / Aktivität",
        "it": "Uscita / attività di gruppo",
        "pl": "Przejażdżka / aktywność grupowa",
        "ru": "Групповая поездка / активность",
        "sq": "Voitje / aktivitet në grup",
        "zh-Hans": "团骑 / 团体活动",
        "nl": "Groepsrit / activiteit",
    },
    "pickup_event_type_group_session": {
        "en": "Group Session / Activity",
        "es": "Sesión / actividad en grupo",
        "fr": "Session / activité de groupe",
        "pt": "Sessão / atividade em grupo",
        "de": "Gruppensession / Aktivität",
        "it": "Sessione / attività di gruppo",
        "pl": "Sesja / aktywność grupowa",
        "ru": "Групповая сессия / активность",
        "sq": "Sesion / aktivitet në grup",
        "zh-Hans": "团体场次 / 活动",
        "nl": "Groepssessie / activiteit",
    },
    "pickup_event_type_race_meet": {
        "en": "Race / Meet",
        "es": "Carrera / Meet",
        "fr": "Course / Meeting",
        "pt": "Corrida / Meet",
        "de": "Rennen / Meeting",
        "it": "Gara / Meeting",
        "pl": "Wyścig / Meet",
        "ru": "Гонка / соревнование",
        "sq": "Gara / Meet",
        "zh-Hans": "赛事 / 运动会",
        "nl": "Race / Meet",
    },
    "pickup_event_type_race_competition": {
        "en": "Race / Competition",
        "es": "Carrera / Competición",
        "fr": "Course / Compétition",
        "pt": "Corrida / Competição",
        "de": "Rennen / Wettbewerb",
        "it": "Gara / Competizione",
        "pl": "Wyścig / Zawody",
        "ru": "Гонка / соревнование",
        "sq": "Gara / Kompeticion",
        "zh-Hans": "赛事 / 竞赛",
        "nl": "Race / wedstrijd",
    },
    "pickup_event_type_practice_training": {
        "en": "Practice / Training",
        "es": "Práctica / Entrenamiento",
        "fr": "Entraînement / Pratique",
        "pt": "Prática / Treino",
        "de": "Übung / Training",
        "it": "Pratica / Allenamento",
        "pl": "Ćwiczenia / Trening",
        "ru": "Практика / Тренировка",
        "sq": "Praktikë / Stërvitje",
        "zh-Hans": "练习 / 训练",
        "nl": "Oefening / training",
    },
    "pickup_event_type_competition": {
        "en": "Competition",
        "es": "Competición",
        "fr": "Compétition",
        "pt": "Competição",
        "de": "Wettbewerb",
        "it": "Competizione",
        "pl": "Zawody",
        "ru": "Соревнование",
        "sq": "Kompeticion",
        "zh-Hans": "竞赛",
        "nl": "Wedstrijd",
    },
    "pickup_form_more_options_subtitle": {
        "en": "Description, skill, welcome, polls, and more",
        "es": "Descripción, nivel, quién puede unirse, encuestas y más",
        "fr": "Description, niveau, bienvenue, sondages et plus",
        "pt": "Descrição, nível, quem é bem-vindo, enquetes e mais",
        "de": "Beschreibung, Level, Willkommen, Umfragen und mehr",
        "it": "Descrizione, livello, chi è il benvenuto, sondaggi e altro",
        "pl": "Opis, poziom, kto mile widziany, ankiety i więcej",
        "ru": "Описание, уровень, кто может, опросы и ещё",
        "sq": "Përshkrim, nivel, mirëseardhje, sondazhe dhe më shumë",
        "zh-Hans": "简介、水平、欢迎对象、投票等",
        "nl": "Beschrijving, niveau, welkom, polls en meer",
    },
}


def main() -> None:
    data = json.loads(XCSTRINGS.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})
    for key, translations in ENTRIES.items():
        strings[key] = {
            "extractionState": "manual",
            "localizations": locs(translations),
        }
    XCSTRINGS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Patched {len(ENTRIES)} keys into {XCSTRINGS}")


if __name__ == "__main__":
    main()
