#!/usr/bin/env python3
"""Localization for Cycling/E-Scooter/Inline Skating sports and reusable subtypes."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XCSTRINGS = ROOT / "GameOn" / "Localizable.xcstrings"
SUPPORTED = ["en", "es", "fr", "pt", "de", "it", "pl", "ru", "sq", "zh-Hans", "nl"]


def unit(value: str) -> dict:
    return {"stringUnit": {"state": "translated", "value": value}}


def locs(translations: dict[str, str]) -> dict:
    return {lang: unit(translations.get(lang, translations["en"])) for lang in SUPPORTED}


ENTRIES: dict[str, dict[str, str]] = {
    "Electric Scooter": {
        "en": "Electric Scooter",
        "es": "Patinete eléctrico",
        "fr": "Trottinette électrique",
        "pt": "Patinete elétrico",
        "de": "E-Scooter",
        "it": "Monopattino elettrico",
        "pl": "Hulajnoga elektryczna",
        "ru": "Электросамокат",
        "sq": "Skuter elektrik",
        "zh-Hans": "电动滑板车",
        "nl": "Elektrische step",
    },
    "E-Scooter": {
        "en": "E-Scooter",
        "es": "E-scooter",
        "fr": "E-trottinette",
        "pt": "E-scooter",
        "de": "E-Scooter",
        "it": "E-scooter",
        "pl": "E-hulajnoga",
        "ru": "Е-самокат",
        "sq": "E-skuter",
        "zh-Hans": "电动滑板车",
        "nl": "E-step",
    },
    "Inline Skating": {
        "en": "Inline Skating",
        "es": "Patinaje en línea",
        "fr": "Roller en ligne",
        "pt": "Patinação em linha",
        "de": "Inlineskaten",
        "it": "Pattinaggio in linea",
        "pl": "Jazda na rolkach",
        "ru": "Роликовые коньки",
        "sq": "Patina në linjë",
        "zh-Hans": "轮滑",
        "nl": "Skeeleren",
    },
    "sport_subtype_picker_cycling": {
        "en": "Cycling Type",
        "es": "Tipo de ciclismo",
        "fr": "Type de cyclisme",
        "pt": "Tipo de ciclismo",
        "de": "Radtyp",
        "it": "Tipo di ciclismo",
        "pl": "Typ kolarstwa",
        "ru": "Тип велоспорта",
        "sq": "Lloji i çiklizmit",
        "zh-Hans": "骑行类型",
        "nl": "Wielrentype",
    },
    "sport_subtype_picker_electric_scooter": {
        "en": "Electric Scooter Type",
        "es": "Tipo de patinete eléctrico",
        "fr": "Type de trottinette",
        "pt": "Tipo de patinete elétrico",
        "de": "E-Scooter-Typ",
        "it": "Tipo di monopattino",
        "pl": "Typ hulajnogi",
        "ru": "Тип электросамоката",
        "sq": "Lloji i skuterit",
        "zh-Hans": "电动滑板车类型",
        "nl": "E-step type",
    },
    "sport_subtype_picker_inline_skating": {
        "en": "Inline Skating Type",
        "es": "Tipo de patinaje",
        "fr": "Type de roller",
        "pt": "Tipo de patinação",
        "de": "Inlineskate-Typ",
        "it": "Tipo di pattinaggio",
        "pl": "Typ jazdy na rolkach",
        "ru": "Тип катания",
        "sq": "Lloji i patinave",
        "zh-Hans": "轮滑类型",
        "nl": "Skeeler-type",
    },
    "sport_subtype_road_cycling": {
        "en": "Road Cycling",
        "es": "Ciclismo de carretera",
        "fr": "Cyclisme sur route",
        "pt": "Ciclismo de estrada",
        "de": "Straßenradsport",
        "it": "Ciclismo su strada",
        "pl": "Kolarstwo szosowe",
        "ru": "Шоссе",
        "sq": "Çiklizëm rruge",
        "zh-Hans": "公路骑行",
        "nl": "Wegwielrennen",
    },
    "sport_subtype_mountain_biking": {
        "en": "Mountain Biking",
        "es": "Ciclismo de montaña",
        "fr": "VTT",
        "pt": "Mountain bike",
        "de": "Mountainbike",
        "it": "Mountain bike",
        "pl": "Kolarstwo górskie",
        "ru": "Маунтинбайк",
        "sq": "Biçikletë mali",
        "zh-Hans": "山地骑行",
        "nl": "Mountainbiken",
    },
    "sport_subtype_gravel": {
        "en": "Gravel",
        "es": "Gravel",
        "fr": "Gravel",
        "pt": "Gravel",
        "de": "Gravel",
        "it": "Gravel",
        "pl": "Gravel",
        "ru": "Гравел",
        "sq": "Gravel",
        "zh-Hans": "砾石骑行",
        "nl": "Gravel",
    },
    "sport_subtype_bmx": {
        "en": "BMX",
        "es": "BMX",
        "fr": "BMX",
        "pt": "BMX",
        "de": "BMX",
        "it": "BMX",
        "pl": "BMX",
        "ru": "BMX",
        "sq": "BMX",
        "zh-Hans": "BMX",
        "nl": "BMX",
    },
    "sport_subtype_e_bike": {
        "en": "E-Bike",
        "es": "Bicicleta eléctrica",
        "fr": "Vélo électrique",
        "pt": "Bicicleta elétrica",
        "de": "E-Bike",
        "it": "E-bike",
        "pl": "E-bike",
        "ru": "Электровелосипед",
        "sq": "E-biçikletë",
        "zh-Hans": "电动自行车",
        "nl": "E-bike",
    },
    "sport_subtype_casual_ride": {
        "en": "Casual Ride",
        "es": "Paseo informal",
        "fr": "Balade",
        "pt": "Passeio casual",
        "de": "Gemütliche Tour",
        "it": "Giro casual",
        "pl": "Spokojna przejażdżka",
        "ru": "Прогулочная поездка",
        "sq": "Udhëtim i qetë",
        "zh-Hans": "休闲骑行",
        "nl": "Ontspannen rit",
    },
    "sport_subtype_other": {
        "en": "Other",
        "es": "Otro",
        "fr": "Autre",
        "pt": "Outro",
        "de": "Sonstiges",
        "it": "Altro",
        "pl": "Inne",
        "ru": "Другое",
        "sq": "Tjetër",
        "zh-Hans": "其他",
        "nl": "Overig",
    },
    "sport_subtype_group_ride": {
        "en": "Group Ride",
        "es": "Salida en grupo",
        "fr": "Sortie de groupe",
        "pt": "Passeio em grupo",
        "de": "Gruppenfahrt",
        "it": "Uscita di gruppo",
        "pl": "Wyjazd grupowy",
        "ru": "Групповая поездка",
        "sq": "Udhëtim grupi",
        "zh-Hans": "团体骑行",
        "nl": "Groepsrit",
    },
    "sport_subtype_street_cruise": {
        "en": "Street / Cruise",
        "es": "Calle / Paseo",
        "fr": "Rue / Balade",
        "pt": "Rua / Passeio",
        "de": "Straße / Cruise",
        "it": "Strada / Cruise",
        "pl": "Ulica / Cruise",
        "ru": "Улица / круиз",
        "sq": "Rrugë / Cruise",
        "zh-Hans": "街道 / 巡航",
        "nl": "Straat / Cruise",
    },
    "sport_subtype_trail_offroad": {
        "en": "Trail / Off-road",
        "es": "Sendero / Off-road",
        "fr": "Sentier / Hors-piste",
        "pt": "Trilha / Off-road",
        "de": "Trail / Offroad",
        "it": "Sentiero / Off-road",
        "pl": "Szlak / Off-road",
        "ru": "Тропа / оффроуд",
        "sq": "Shtigje / Off-road",
        "zh-Hans": "越野 / 小径",
        "nl": "Trail / Off-road",
    },
    "sport_subtype_recreational": {
        "en": "Recreational",
        "es": "Recreativo",
        "fr": "Loisir",
        "pt": "Recreativo",
        "de": "Freizeit",
        "it": "Ricreativo",
        "pl": "Rekreacyjny",
        "ru": "Любительский",
        "sq": "Rekreative",
        "zh-Hans": "休闲",
        "nl": "Recreatief",
    },
    "sport_subtype_fitness": {
        "en": "Fitness",
        "es": "Fitness",
        "fr": "Fitness",
        "pt": "Fitness",
        "de": "Fitness",
        "it": "Fitness",
        "pl": "Fitness",
        "ru": "Фитнес",
        "sq": "Fitnes",
        "zh-Hans": "健身",
        "nl": "Fitness",
    },
    "sport_subtype_urban_street": {
        "en": "Urban / Street",
        "es": "Urbano / Calle",
        "fr": "Urbain / Rue",
        "pt": "Urbano / Rua",
        "de": "Urban / Straße",
        "it": "Urbano / Strada",
        "pl": "Miejski / Ulica",
        "ru": "Город / улица",
        "sq": "Urban / Rrugë",
        "zh-Hans": "都市 / 街头",
        "nl": "Urban / Straat",
    },
    "sport_subtype_speed": {
        "en": "Speed",
        "es": "Velocidad",
        "fr": "Vitesse",
        "pt": "Velocidade",
        "de": "Speed",
        "it": "Velocità",
        "pl": "Szybkość",
        "ru": "Скорость",
        "sq": "Shpejtësi",
        "zh-Hans": "速度",
        "nl": "Speed",
    },
    "sport_subtype_identity_format": {
        "en": "%@ · %@",
        "es": "%@ · %@",
        "fr": "%@ · %@",
        "pt": "%@ · %@",
        "de": "%@ · %@",
        "it": "%@ · %@",
        "pl": "%@ · %@",
        "ru": "%@ · %@",
        "sq": "%@ · %@",
        "zh-Hans": "%@ · %@",
        "nl": "%@ · %@",
    },
    "sport_subtype_title_road_cycling": {
        "en": "Road Ride",
        "es": "Salida de carretera",
        "fr": "Sortie route",
        "pt": "Passeio de estrada",
        "de": "Straßentour",
        "it": "Uscita su strada",
        "pl": "Szosowa przejażdżka",
        "ru": "Шоссейная поездка",
        "sq": "Udhëtim rruge",
        "zh-Hans": "公路骑行",
        "nl": "Wegrit",
    },
    "sport_subtype_title_mountain_biking": {
        "en": "Mountain Bike Ride",
        "es": "Ruta de mountain bike",
        "fr": "Sortie VTT",
        "pt": "Passeio de mountain bike",
        "de": "Mountainbike-Tour",
        "it": "Uscita MTB",
        "pl": "Wyprawa MTB",
        "ru": "Маунтинбайк-поездка",
        "sq": "Udhëtim MTB",
        "zh-Hans": "山地骑行",
        "nl": "Mountainbikerit",
    },
    "sport_subtype_title_gravel": {
        "en": "Gravel Ride",
        "es": "Salida gravel",
        "fr": "Sortie gravel",
        "pt": "Passeio gravel",
        "de": "Gravel-Tour",
        "it": "Uscita gravel",
        "pl": "Przejażdżka gravel",
        "ru": "Гравел-поездка",
        "sq": "Udhëtim gravel",
        "zh-Hans": "砾石骑行",
        "nl": "Gravelrit",
    },
    "sport_subtype_title_bmx": {
        "en": "BMX Ride",
        "es": "Sesión de BMX",
        "fr": "Session BMX",
        "pt": "Sessão de BMX",
        "de": "BMX-Session",
        "it": "Sessione BMX",
        "pl": "Sesja BMX",
        "ru": "BMX-сессия",
        "sq": "Seancë BMX",
        "zh-Hans": "BMX 骑行",
        "nl": "BMX-rit",
    },
    "sport_subtype_title_e_bike": {
        "en": "E-Bike Ride",
        "es": "Paseo en e-bike",
        "fr": "Sortie e-bike",
        "pt": "Passeio de e-bike",
        "de": "E-Bike-Tour",
        "it": "Uscita e-bike",
        "pl": "Przejażdżka e-bike",
        "ru": "Поездка на электровелосипеде",
        "sq": "Udhëtim e-bike",
        "zh-Hans": "电动自行车骑行",
        "nl": "E-bike rit",
    },
    "sport_subtype_title_casual_ride": {
        "en": "Casual Ride",
        "es": "Paseo informal",
        "fr": "Balade",
        "pt": "Passeio casual",
        "de": "Gemütliche Tour",
        "it": "Giro casual",
        "pl": "Spokojna przejażdżka",
        "ru": "Прогулочная поездка",
        "sq": "Udhëtim i qetë",
        "zh-Hans": "休闲骑行",
        "nl": "Ontspannen rit",
    },
    "sport_subtype_title_cycling_other": {
        "en": "Group Ride",
        "es": "Salida en grupo",
        "fr": "Sortie de groupe",
        "pt": "Passeio em grupo",
        "de": "Gruppenfahrt",
        "it": "Uscita di gruppo",
        "pl": "Wyjazd grupowy",
        "ru": "Групповая поездка",
        "sq": "Udhëtim grupi",
        "zh-Hans": "团体骑行",
        "nl": "Groepsrit",
    },
    "sport_subtype_title_escooter_group_ride": {
        "en": "E-Scooter Group Ride",
        "es": "Salida en grupo de patinete",
        "fr": "Sortie trottinette en groupe",
        "pt": "Passeio em grupo de patinete",
        "de": "E-Scooter-Gruppenfahrt",
        "it": "Uscita di gruppo in monopattino",
        "pl": "Grupowy przejazd hulajnogą",
        "ru": "Групповая поездка на самокатах",
        "sq": "Udhëtim grupi me skuter",
        "zh-Hans": "电动滑板车团体骑行",
        "nl": "E-step groepsrit",
    },
    "sport_subtype_title_escooter_street": {
        "en": "E-Scooter Ride",
        "es": "Paseo en patinete eléctrico",
        "fr": "Balade en trottinette",
        "pt": "Passeio de patinete elétrico",
        "de": "E-Scooter-Tour",
        "it": "Giro in monopattino",
        "pl": "Przejazd hulajnogą",
        "ru": "Поездка на электросамокате",
        "sq": "Udhëtim me skuter",
        "zh-Hans": "电动滑板车骑行",
        "nl": "E-step rit",
    },
    "sport_subtype_title_escooter_trail": {
        "en": "E-Scooter Trail Ride",
        "es": "Ruta off-road en patinete",
        "fr": "Sortie trottinette hors-piste",
        "pt": "Trilha de patinete elétrico",
        "de": "E-Scooter-Trail",
        "it": "Uscita monopattino off-road",
        "pl": "Off-road hulajnogą",
        "ru": "Тропа на электросамокате",
        "sq": "Udhëtim skuter off-road",
        "zh-Hans": "电动滑板车越野",
        "nl": "E-step trailrit",
    },
    "sport_subtype_title_escooter_other": {
        "en": "E-Scooter Ride",
        "es": "Paseo en patinete eléctrico",
        "fr": "Balade en trottinette",
        "pt": "Passeio de patinete elétrico",
        "de": "E-Scooter-Tour",
        "it": "Giro in monopattino",
        "pl": "Przejazd hulajnogą",
        "ru": "Поездка на электросамокате",
        "sq": "Udhëtim me skuter",
        "zh-Hans": "电动滑板车骑行",
        "nl": "E-step rit",
    },
    "sport_subtype_title_inline_recreational": {
        "en": "Inline Skating Session",
        "es": "Sesión de patinaje",
        "fr": "Session de roller",
        "pt": "Sessão de patinação",
        "de": "Inlineskate-Session",
        "it": "Sessione di pattinaggio",
        "pl": "Sesja na rolkach",
        "ru": "Сессия на роликах",
        "sq": "Seancë patinash",
        "zh-Hans": "轮滑活动",
        "nl": "Skeelersessie",
    },
    "sport_subtype_title_inline_fitness": {
        "en": "Inline Skating Fitness",
        "es": "Patinaje fitness",
        "fr": "Roller fitness",
        "pt": "Patinação fitness",
        "de": "Inlineskate-Fitness",
        "it": "Pattinaggio fitness",
        "pl": "Fitness na rolkach",
        "ru": "Фитнес на роликах",
        "sq": "Fitnes me patina",
        "zh-Hans": "轮滑健身",
        "nl": "Skeeler-fitness",
    },
    "sport_subtype_title_inline_urban": {
        "en": "Urban Inline Skating",
        "es": "Patinaje urbano",
        "fr": "Roller urbain",
        "pt": "Patinação urbana",
        "de": "Urban Inlineskaten",
        "it": "Pattinaggio urbano",
        "pl": "Rolki miejskie",
        "ru": "Городские ролики",
        "sq": "Patina urbane",
        "zh-Hans": "都市轮滑",
        "nl": "Urban skeeleren",
    },
    "sport_subtype_title_inline_speed": {
        "en": "Speed Skating Session",
        "es": "Sesión de velocidad",
        "fr": "Session vitesse",
        "pt": "Sessão de velocidade",
        "de": "Speedskate-Session",
        "it": "Sessione speed",
        "pl": "Sesja speed",
        "ru": "Скоростная сессия",
        "sq": "Seancë shpejtësie",
        "zh-Hans": "速度轮滑",
        "nl": "Speed-sessie",
    },
    "sport_subtype_title_inline_other": {
        "en": "Inline Skating Session",
        "es": "Sesión de patinaje",
        "fr": "Session de roller",
        "pt": "Sessão de patinação",
        "de": "Inlineskate-Session",
        "it": "Sessione di pattinaggio",
        "pl": "Sesja na rolkach",
        "ru": "Сессия на роликах",
        "sq": "Seancë patinash",
        "zh-Hans": "轮滑活动",
        "nl": "Skeelersessie",
    },
}


def main() -> None:
    data = json.loads(XCSTRINGS.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})
    for key, translations in ENTRIES.items():
        entry = strings.get(key) or {}
        entry["localizations"] = locs(translations)
        strings[key] = entry
    XCSTRINGS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"patched {len(ENTRIES)} keys")


if __name__ == "__main__":
    main()
