#!/usr/bin/env python3
"""Localizations for Team Saved + Recent Locations picker."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XCSTRINGS = ROOT / "GameOn" / "Localizable.xcstrings"
SUPPORTED = ["en", "es", "fr", "pt", "de", "it", "pl", "ru", "sq", "zh-Hans", "nl"]


def unit(value: str) -> dict:
    return {"stringUnit": {"state": "translated", "value": value}}


def locs(translations: dict[str, str]) -> dict:
    return {lang: unit(translations[lang]) for lang in SUPPORTED if lang in translations}


ENTRIES: dict[str, dict[str, str]] = {
    "team_location_choose_title": {
        "en": "Choose Location",
        "es": "Elegir ubicación",
        "fr": "Choisir un lieu",
        "pt": "Escolher local",
        "de": "Ort wählen",
        "it": "Scegli luogo",
        "pl": "Wybierz lokalizację",
        "ru": "Выбрать место",
        "sq": "Zgjidh vendndodhjen",
        "zh-Hans": "选择地点",
        "nl": "Locatie kiezen",
    },
    "team_location_saved_section": {
        "en": "Saved Locations",
        "es": "Ubicaciones guardadas",
        "fr": "Lieux enregistrés",
        "pt": "Locais salvos",
        "de": "Gespeicherte Orte",
        "it": "Luoghi salvati",
        "pl": "Zapisane lokalizacje",
        "ru": "Сохранённые места",
        "sq": "Vendndodhje të ruajtura",
        "zh-Hans": "已保存地点",
        "nl": "Opgeslagen locaties",
    },
    "team_location_recent_section": {
        "en": "Recent Locations",
        "es": "Ubicaciones recientes",
        "fr": "Lieux récents",
        "pt": "Locais recentes",
        "de": "Zuletzt verwendet",
        "it": "Luoghi recenti",
        "pl": "Ostatnie lokalizacje",
        "ru": "Недавние места",
        "sq": "Vendndodhje të fundit",
        "zh-Hans": "最近地点",
        "nl": "Recente locaties",
    },
    "team_location_saved_empty": {
        "en": "No saved locations yet.",
        "es": "Aún no hay ubicaciones guardadas.",
        "fr": "Aucun lieu enregistré pour le moment.",
        "pt": "Ainda não há locais salvos.",
        "de": "Noch keine gespeicherten Orte.",
        "it": "Nessun luogo salvato.",
        "pl": "Brak zapisanych lokalizacji.",
        "ru": "Пока нет сохранённых мест.",
        "sq": "Ende pa vendndodhje të ruajtura.",
        "zh-Hans": "暂无已保存地点。",
        "nl": "Nog geen opgeslagen locaties.",
    },
    "team_location_recent_empty": {
        "en": "Locations you use will appear here.",
        "es": "Las ubicaciones que uses aparecerán aquí.",
        "fr": "Les lieux que vous utilisez apparaîtront ici.",
        "pt": "Os locais que você usar aparecerão aqui.",
        "de": "Von dir genutzte Orte erscheinen hier.",
        "it": "I luoghi che usi appariranno qui.",
        "pl": "Używane lokalizacje pojawią się tutaj.",
        "ru": "Используемые места появятся здесь.",
        "sq": "Vendndodhjet që përdorni do të shfaqen këtu.",
        "zh-Hans": "你使用过的地点会出现在这里。",
        "nl": "Locaties die je gebruikt verschijnen hier.",
    },
    "team_location_search": {
        "en": "Search for a location",
        "es": "Buscar una ubicación",
        "fr": "Rechercher un lieu",
        "pt": "Pesquisar um local",
        "de": "Ort suchen",
        "it": "Cerca un luogo",
        "pl": "Szukaj lokalizacji",
        "ru": "Найти место",
        "sq": "Kërko një vendndodhje",
        "zh-Hans": "搜索地点",
        "nl": "Zoek een locatie",
    },
    "team_location_add_new": {
        "en": "Add new location",
        "es": "Añadir nueva ubicación",
        "fr": "Ajouter un nouveau lieu",
        "pt": "Adicionar novo local",
        "de": "Neuen Ort hinzufügen",
        "it": "Aggiungi nuovo luogo",
        "pl": "Dodaj nową lokalizację",
        "ru": "Добавить новое место",
        "sq": "Shto vendndodhje të re",
        "zh-Hans": "添加新地点",
        "nl": "Nieuwe locatie toevoegen",
    },
    "team_location_enter_manually": {
        "en": "Enter manually",
        "es": "Introducir manualmente",
        "fr": "Saisir manuellement",
        "pt": "Inserir manualmente",
        "de": "Manuell eingeben",
        "it": "Inserisci manualmente",
        "pl": "Wprowadź ręcznie",
        "ru": "Ввести вручную",
        "sq": "Fut manualisht",
        "zh-Hans": "手动输入",
        "nl": "Handmatig invoeren",
    },
    "team_location_save_for_team": {
        "en": "Save for this Team",
        "es": "Guardar para este equipo",
        "fr": "Enregistrer pour cette équipe",
        "pt": "Salvar para esta equipe",
        "de": "Für dieses Team speichern",
        "it": "Salva per questa squadra",
        "pl": "Zapisz dla tej drużyny",
        "ru": "Сохранить для этой команды",
        "sq": "Ruaje për këtë ekip",
        "zh-Hans": "为此队伍保存",
        "nl": "Opslaan voor dit team",
    },
    "team_location_use_without_saving": {
        "en": "Use without saving",
        "es": "Usar sin guardar",
        "fr": "Utiliser sans enregistrer",
        "pt": "Usar sem salvar",
        "de": "Ohne Speichern verwenden",
        "it": "Usa senza salvare",
        "pl": "Użyj bez zapisywania",
        "ru": "Использовать без сохранения",
        "sq": "Përdore pa ruajtur",
        "zh-Hans": "不保存直接使用",
        "nl": "Gebruik zonder op te slaan",
    },
    "team_location_save_prompt_title": {
        "en": "Save for this Team?",
        "es": "¿Guardar para este equipo?",
        "fr": "Enregistrer pour cette équipe ?",
        "pt": "Salvar para esta equipe?",
        "de": "Für dieses Team speichern?",
        "it": "Salvare per questa squadra?",
        "pl": "Zapisać dla tej drużyny?",
        "ru": "Сохранить для этой команды?",
        "sq": "Të ruhet për këtë ekip?",
        "zh-Hans": "为此队伍保存？",
        "nl": "Opslaan voor dit team?",
    },
    "team_location_save_prompt_body": {
        "en": "Give this place a Team nickname, or use it once without saving.",
        "es": "Ponle un apodo del equipo o úsalo una vez sin guardar.",
        "fr": "Donnez un surnom d’équipe à ce lieu, ou utilisez-le une fois sans l’enregistrer.",
        "pt": "Dê um apelido do time a este local ou use uma vez sem salvar.",
        "de": "Gib diesem Ort einen Team-Spitznamen oder nutze ihn einmal ohne Speichern.",
        "it": "Dai a questo luogo un soprannome di squadra, oppure usalo una volta senza salvarlo.",
        "pl": "Nadaj tej lokalizacji nazwę drużynową albo użyj raz bez zapisywania.",
        "ru": "Дайте месту командное название или используйте один раз без сохранения.",
        "sq": "Jepi një nofkë ekipi këtij vendi, ose përdore një herë pa e ruajtur.",
        "zh-Hans": "为该地点设置队伍昵称，或不保存直接使用一次。",
        "nl": "Geef deze plek een teamnaam, of gebruik hem één keer zonder op te slaan.",
    },
    "team_location_nickname": {
        "en": "Location nickname",
        "es": "Apodo de la ubicación",
        "fr": "Surnom du lieu",
        "pt": "Apelido do local",
        "de": "Orts-Spitzname",
        "it": "Soprannome del luogo",
        "pl": "Nazwa lokalizacji",
        "ru": "Название места",
        "sq": "Nofka e vendndodhjes",
        "zh-Hans": "地点昵称",
        "nl": "Locatiebijnaam",
    },
    "team_location_nickname_placeholder": {
        "en": "e.g. Home Field",
        "es": "p. ej. Campo local",
        "fr": "ex. Terrain domicile",
        "pt": "ex.: Campo da casa",
        "de": "z. B. Heimfeld",
        "it": "es. Campo di casa",
        "pl": "np. Boisko domowe",
        "ru": "напр. Домашнее поле",
        "sq": "p.sh. Fusha e shtëpisë",
        "zh-Hans": "例如：主场",
        "nl": "bijv. Thuisveld",
    },
    "team_location_default_badge": {
        "en": "Default",
        "es": "Predeterminada",
        "fr": "Par défaut",
        "pt": "Padrão",
        "de": "Standard",
        "it": "Predefinito",
        "pl": "Domyślna",
        "ru": "По умолчанию",
        "sq": "Parazgjedhur",
        "zh-Hans": "默认",
        "nl": "Standaard",
    },
    "team_location_set_default": {
        "en": "Set as Default",
        "es": "Establecer como predeterminada",
        "fr": "Définir par défaut",
        "pt": "Definir como padrão",
        "de": "Als Standard festlegen",
        "it": "Imposta come predefinito",
        "pl": "Ustaw jako domyślną",
        "ru": "Сделать по умолчанию",
        "sq": "Cakto si parazgjedhje",
        "zh-Hans": "设为默认",
        "nl": "Instellen als standaard",
    },
    "team_location_edit": {
        "en": "Edit",
        "es": "Editar",
        "fr": "Modifier",
        "pt": "Editar",
        "de": "Bearbeiten",
        "it": "Modifica",
        "pl": "Edytuj",
        "ru": "Изменить",
        "sq": "Ndrysho",
        "zh-Hans": "编辑",
        "nl": "Bewerken",
    },
    "team_location_remove_saved": {
        "en": "Remove saved location",
        "es": "Eliminar ubicación guardada",
        "fr": "Supprimer le lieu enregistré",
        "pt": "Remover local salvo",
        "de": "Gespeicherten Ort entfernen",
        "it": "Rimuovi luogo salvato",
        "pl": "Usuń zapisaną lokalizację",
        "ru": "Удалить сохранённое место",
        "sq": "Hiq vendndodhjen e ruajtur",
        "zh-Hans": "移除已保存地点",
        "nl": "Opgeslagen locatie verwijderen",
    },
    "team_location_clear_recent": {
        "en": "Clear recent locations",
        "es": "Borrar ubicaciones recientes",
        "fr": "Effacer les lieux récents",
        "pt": "Limpar locais recentes",
        "de": "Zuletzt verwendete Orte löschen",
        "it": "Cancella luoghi recenti",
        "pl": "Wyczyść ostatnie lokalizacje",
        "ru": "Очистить недавние места",
        "sq": "Pastro vendndodhjet e fundit",
        "zh-Hans": "清除最近地点",
        "nl": "Recente locaties wissen",
    },
    "team_location_clear_recent_confirm": {
        "en": "Clear recent Team locations? Saved locations stay.",
        "es": "¿Borrar ubicaciones recientes del equipo? Las guardadas se mantienen.",
        "fr": "Effacer les lieux récents de l’équipe ? Les lieux enregistrés restent.",
        "pt": "Limpar locais recentes da equipe? Os salvos permanecem.",
        "de": "Zuletzt verwendete Team-Orte löschen? Gespeicherte Orte bleiben.",
        "it": "Cancellare i luoghi recenti della squadra? Quelli salvati restano.",
        "pl": "Wyczyścić ostatnie lokalizacje drużyny? Zapisane pozostaną.",
        "ru": "Очистить недавние места команды? Сохранённые останутся.",
        "sq": "Të pastrohen vendndodhjet e fundit të ekipit? Të ruajturat mbeten.",
        "zh-Hans": "清除队伍最近地点？已保存地点会保留。",
        "nl": "Recente teamlocaties wissen? Opgeslagen locaties blijven.",
    },
    "team_location_used_recently": {
        "en": "Used recently",
        "es": "Usada recientemente",
        "fr": "Utilisé récemment",
        "pt": "Usado recentemente",
        "de": "Kürzlich verwendet",
        "it": "Usato di recente",
        "pl": "Użyto niedawno",
        "ru": "Использовано недавно",
        "sq": "Përdorur së fundmi",
        "zh-Hans": "最近使用",
        "nl": "Onlangs gebruikt",
    },
    "team_location_used_yesterday": {
        "en": "Used yesterday",
        "es": "Usada ayer",
        "fr": "Utilisé hier",
        "pt": "Usado ontem",
        "de": "Gestern verwendet",
        "it": "Usato ieri",
        "pl": "Użyto wczoraj",
        "ru": "Использовано вчера",
        "sq": "Përdorur dje",
        "zh-Hans": "昨天使用",
        "nl": "Gisteren gebruikt",
    },
    "team_location_used_last_week": {
        "en": "Used last week",
        "es": "Usada la semana pasada",
        "fr": "Utilisé la semaine dernière",
        "pt": "Usado na semana passada",
        "de": "Letzte Woche verwendet",
        "it": "Usato la scorsa settimana",
        "pl": "Użyto w zeszłym tygodniu",
        "ru": "Использовано на прошлой неделе",
        "sq": "Përdorur javën e kaluar",
        "zh-Hans": "上周使用",
        "nl": "Vorige week gebruikt",
    },
    "team_location_used_times_format": {
        "en": "Used %lld times",
        "es": "Usada %lld veces",
        "fr": "Utilisé %lld fois",
        "pt": "Usado %lld vezes",
        "de": "%lld Mal verwendet",
        "it": "Usato %lld volte",
        "pl": "Użyto %lld razy",
        "ru": "Использовано %lld раз",
        "sq": "Përdorur %lld herë",
        "zh-Hans": "使用了 %lld 次",
        "nl": "%lld keer gebruikt",
    },
    "team_location_a11y_saved": {
        "en": "Saved location",
        "es": "Ubicación guardada",
        "fr": "Lieu enregistré",
        "pt": "Local salvo",
        "de": "Gespeicherter Ort",
        "it": "Luogo salvato",
        "pl": "Zapisana lokalizacja",
        "ru": "Сохранённое место",
        "sq": "Vendndodhje e ruajtur",
        "zh-Hans": "已保存地点",
        "nl": "Opgeslagen locatie",
    },
    "team_location_a11y_recent": {
        "en": "Recent location",
        "es": "Ubicación reciente",
        "fr": "Lieu récent",
        "pt": "Local recente",
        "de": "Zuletzt verwendeter Ort",
        "it": "Luogo recente",
        "pl": "Ostatnia lokalizacja",
        "ru": "Недавнее место",
        "sq": "Vendndodhje e fundit",
        "zh-Hans": "最近地点",
        "nl": "Recente locatie",
    },
    "team_location_a11y_default": {
        "en": "Default Team location",
        "es": "Ubicación predeterminada del equipo",
        "fr": "Lieu par défaut de l’équipe",
        "pt": "Local padrão da equipe",
        "de": "Standard-Teamort",
        "it": "Luogo predefinito della squadra",
        "pl": "Domyślna lokalizacja drużyny",
        "ru": "Место команды по умолчанию",
        "sq": "Vendndodhja e parazgjedhur e ekipit",
        "zh-Hans": "默认队伍地点",
        "nl": "Standaard teamlocatie",
    },
    "team_location_incomplete": {
        "en": "This location is incomplete.",
        "es": "Esta ubicación está incompleta.",
        "fr": "Ce lieu est incomplet.",
        "pt": "Este local está incompleto.",
        "de": "Dieser Ort ist unvollständig.",
        "it": "Questo luogo è incompleto.",
        "pl": "Ta lokalizacja jest niekompletna.",
        "ru": "Это место указано неполностью.",
        "sq": "Kjo vendndodhje është e paplotë.",
        "zh-Hans": "该地点信息不完整。",
        "nl": "Deze locatie is onvolledig.",
    },
    "team_location_geocode_failed": {
        "en": "Could not find that address on the map.",
        "es": "No se pudo encontrar esa dirección en el mapa.",
        "fr": "Impossible de trouver cette adresse sur la carte.",
        "pt": "Não foi possível encontrar esse endereço no mapa.",
        "de": "Diese Adresse konnte auf der Karte nicht gefunden werden.",
        "it": "Impossibile trovare questo indirizzo sulla mappa.",
        "pl": "Nie udało się znaleźć tego adresu na mapie.",
        "ru": "Не удалось найти этот адрес на карте.",
        "sq": "Nuk u gjet ajo adresë në hartë.",
        "zh-Hans": "无法在地图上找到该地址。",
        "nl": "Kon dat adres niet op de kaart vinden.",
    },
    "team_location_place_name": {
        "en": "Place name",
        "es": "Nombre del lugar",
        "fr": "Nom du lieu",
        "pt": "Nome do local",
        "de": "Ortsname",
        "it": "Nome del luogo",
        "pl": "Nazwa miejsca",
        "ru": "Название места",
        "sq": "Emri i vendit",
        "zh-Hans": "地点名称",
        "nl": "Plaatsnaam",
    },
}


def main() -> None:
    data = json.loads(XCSTRINGS.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})
    for key, translations in ENTRIES.items():
        entry = strings.get(key, {"extractionState": "manual", "localizations": {}})
        entry["extractionState"] = "manual"
        locs_map = entry.setdefault("localizations", {})
        for lang, payload in locs(translations).items():
            locs_map[lang] = payload
        strings[key] = entry
    XCSTRINGS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Patched {len(ENTRIES)} keys into Localizable.xcstrings")


if __name__ == "__main__":
    main()
