#!/usr/bin/env python3
"""Localization for Discoverable Fan Teams on Play → Places."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XCSTRINGS = ROOT / "GameOn" / "Localizable.xcstrings"
SUPPORTED = ["en", "es", "fr", "pt", "de", "it", "pl", "ru", "sq", "zh-Hans", "nl"]


def unit(value: str) -> dict:
    return {"stringUnit": {"state": "translated", "value": value}}


def locs(translations: dict[str, str]) -> dict:
    return {lang: unit(translations.get(lang, translations["en"])) for lang in SUPPORTED}


ENTRIES: dict[str, dict[str, str]] = {
    "team_discovery_section_title": {
        "en": "Discovery",
        "es": "Descubrimiento",
        "fr": "Découverte",
        "pt": "Descoberta",
        "de": "Entdeckung",
        "it": "Scoperta",
        "pl": "Odkrywanie",
        "ru": "Обнаружение",
        "sq": "Zbulimi",
        "zh-Hans": "发现",
        "nl": "Ontdekking",
    },
    "team_discovery_show_on_discover": {
        "en": "Show this Team on Discover",
        "es": "Mostrar este equipo en Descubrir",
        "fr": "Afficher cette équipe dans Découvrir",
        "pt": "Mostrar esta equipe no Descobrir",
        "de": "Dieses Team in Entdecken anzeigen",
        "it": "Mostra questa squadra in Scopri",
        "pl": "Pokaż ten zespół w Odkrywaj",
        "ru": "Показывать эту команду в Обзоре",
        "sq": "Shfaq këtë ekip në Zbulo",
        "zh-Hans": "在发现中显示此队伍",
        "nl": "Toon dit team in Ontdekken",
    },
    "team_discovery_location_title": {
        "en": "Team Location",
        "es": "Ubicación del equipo",
        "fr": "Lieu de l’équipe",
        "pt": "Local da equipe",
        "de": "Teamstandort",
        "it": "Posizione della squadra",
        "pl": "Lokalizacja zespołu",
        "ru": "Место команды",
        "sq": "Vendndodhja e ekipit",
        "zh-Hans": "队伍位置",
        "nl": "Teamlocatie",
    },
    "team_discovery_add_location": {
        "en": "Add Location",
        "es": "Añadir ubicación",
        "fr": "Ajouter un lieu",
        "pt": "Adicionar local",
        "de": "Standort hinzufügen",
        "it": "Aggiungi posizione",
        "pl": "Dodaj lokalizację",
        "ru": "Добавить место",
        "sq": "Shto vendndodhjen",
        "zh-Hans": "添加位置",
        "nl": "Locatie toevoegen",
    },
    "team_discovery_change_location": {
        "en": "Change Location",
        "es": "Cambiar ubicación",
        "fr": "Modifier le lieu",
        "pt": "Alterar local",
        "de": "Standort ändern",
        "it": "Cambia posizione",
        "pl": "Zmień lokalizację",
        "ru": "Изменить место",
        "sq": "Ndrysho vendndodhjen",
        "zh-Hans": "更改位置",
        "nl": "Locatie wijzigen",
    },
    "team_discovery_remove_location": {
        "en": "Remove Location",
        "es": "Quitar ubicación",
        "fr": "Supprimer le lieu",
        "pt": "Remover local",
        "de": "Standort entfernen",
        "it": "Rimuovi posizione",
        "pl": "Usuń lokalizację",
        "ru": "Удалить место",
        "sq": "Hiq vendndodhjen",
        "zh-Hans": "移除位置",
        "nl": "Locatie verwijderen",
    },
    "team_discovery_search_address": {
        "en": "Search address or place",
        "es": "Buscar dirección o lugar",
        "fr": "Rechercher une adresse ou un lieu",
        "pt": "Pesquisar endereço ou lugar",
        "de": "Adresse oder Ort suchen",
        "it": "Cerca indirizzo o luogo",
        "pl": "Szukaj adresu lub miejsca",
        "ru": "Поиск адреса или места",
        "sq": "Kërko adresë ose vend",
        "zh-Hans": "搜索地址或地点",
        "nl": "Zoek adres of plaats",
    },
    "team_discovery_choose_on_map": {
        "en": "Choose on Map",
        "es": "Elegir en el mapa",
        "fr": "Choisir sur la carte",
        "pt": "Escolher no mapa",
        "de": "Auf der Karte wählen",
        "it": "Scegli sulla mappa",
        "pl": "Wybierz na mapie",
        "ru": "Выбрать на карте",
        "sq": "Zgjidh në hartë",
        "zh-Hans": "在地图上选择",
        "nl": "Kies op de kaart",
    },
    "team_discovery_use_this_location": {
        "en": "Use This Location",
        "es": "Usar esta ubicación",
        "fr": "Utiliser ce lieu",
        "pt": "Usar este local",
        "de": "Diesen Standort verwenden",
        "it": "Usa questa posizione",
        "pl": "Użyj tej lokalizacji",
        "ru": "Использовать это место",
        "sq": "Përdor këtë vendndodhje",
        "zh-Hans": "使用此位置",
        "nl": "Gebruik deze locatie",
    },
    "team_discovery_looking_for_players": {
        "en": "Looking for Players",
        "es": "Buscando jugadores",
        "fr": "Recherche de joueurs",
        "pt": "Procurando jogadores",
        "de": "Spieler gesucht",
        "it": "Cerca giocatori",
        "pl": "Szukamy zawodników",
        "ru": "Ищем игроков",
        "sq": "Kërkojmë lojtarë",
        "zh-Hans": "正在招募队员",
        "nl": "Op zoek naar spelers",
    },
    "team_discovery_location_privacy": {
        "en": "This location may be visible to people discovering your Team.",
        "es": "Esta ubicación puede ser visible para quienes descubran tu equipo.",
        "fr": "Ce lieu peut être visible par les personnes qui découvrent votre équipe.",
        "pt": "Este local pode ficar visível para quem descobrir sua equipe.",
        "de": "Dieser Standort kann für Personen sichtbar sein, die dein Team entdecken.",
        "it": "Questa posizione può essere visibile a chi scopre la tua squadra.",
        "pl": "Ta lokalizacja może być widoczna dla osób odkrywających Twój zespół.",
        "ru": "Это место может быть видно людям, которые находят вашу команду.",
        "sq": "Kjo vendndodhje mund të jetë e dukshme për njerëzit që zbulojnë ekipin tuaj.",
        "zh-Hans": "发现你队伍的人可能会看到此位置。",
        "nl": "Deze locatie kan zichtbaar zijn voor mensen die je team ontdekken.",
    },
    "team_discovery_location_required": {
        "en": "Choose a Team location before showing this Team on Discover.",
        "es": "Elige una ubicación del equipo antes de mostrarlo en Descubrir.",
        "fr": "Choisissez un lieu d’équipe avant d’afficher cette équipe dans Découvrir.",
        "pt": "Escolha um local da equipe antes de mostrá-la no Descobrir.",
        "de": "Wähle einen Teamstandort, bevor du dieses Team in Entdecken anzeigst.",
        "it": "Scegli una posizione della squadra prima di mostrarla in Scopri.",
        "pl": "Wybierz lokalizację zespołu, zanim pokażesz go w Odkrywaj.",
        "ru": "Выберите место команды, прежде чем показывать её в Обзоре.",
        "sq": "Zgjidhni një vendndodhje ekipi para se ta shfaqni në Zbulo.",
        "zh-Hans": "在发现中显示此队伍前，请先选择队伍位置。",
        "nl": "Kies een teamlocatie voordat je dit team in Ontdekken toont.",
    },
    "team_discovery_general_area": {
        "en": "General Area",
        "es": "Zona general",
        "fr": "Zone générale",
        "pt": "Área geral",
        "de": "Allgemeiner Bereich",
        "it": "Zona generale",
        "pl": "Obszar ogólny",
        "ru": "Общий район",
        "sq": "Zonë e përgjithshme",
        "zh-Hans": "大致区域",
        "nl": "Algemeen gebied",
    },
    "team_discovery_specific_location": {
        "en": "Specific Location",
        "es": "Ubicación específica",
        "fr": "Lieu précis",
        "pt": "Local específico",
        "de": "Genauer Standort",
        "it": "Posizione specifica",
        "pl": "Dokładna lokalizacja",
        "ru": "Точное место",
        "sq": "Vendndodhje e saktë",
        "zh-Hans": "具体位置",
        "nl": "Specifieke locatie",
    },
    "discover_status_places_and_teams_format": {
        "en": "%lld places · %lld Teams",
        "es": "%lld lugares · %lld equipos",
        "fr": "%lld lieux · %lld équipes",
        "pt": "%lld lugares · %lld equipes",
        "de": "%lld Orte · %lld Teams",
        "it": "%lld luoghi · %lld squadre",
        "pl": "%lld miejsc · %lld zespołów",
        "ru": "%lld мест · %lld команд",
        "sq": "%lld vende · %lld ekipe",
        "zh-Hans": "%lld 个地点 · %lld 支队伍",
        "nl": "%lld plekken · %lld teams",
    },
    "discover_status_team_one": {
        "en": "1 Team nearby",
        "es": "1 equipo cerca",
        "fr": "1 équipe à proximité",
        "pt": "1 equipe por perto",
        "de": "1 Team in der Nähe",
        "it": "1 squadra nelle vicinanze",
        "pl": "1 zespół w pobliżu",
        "ru": "1 команда рядом",
        "sq": "1 ekip afër",
        "zh-Hans": "附近 1 支队伍",
        "nl": "1 team in de buurt",
    },
    "discover_status_team_other_format": {
        "en": "%lld Teams nearby",
        "es": "%lld equipos cerca",
        "fr": "%lld équipes à proximité",
        "pt": "%lld equipes por perto",
        "de": "%lld Teams in der Nähe",
        "it": "%lld squadre nelle vicinanze",
        "pl": "%lld zespołów w pobliżu",
        "ru": "%lld команд рядом",
        "sq": "%lld ekipe afër",
        "zh-Hans": "附近 %lld 支队伍",
        "nl": "%lld teams in de buurt",
    },
    "discover_status_no_teams_nearby": {
        "en": "No Teams nearby",
        "es": "No hay equipos cerca",
        "fr": "Aucune équipe à proximité",
        "pt": "Nenhuma equipe por perto",
        "de": "Keine Teams in der Nähe",
        "it": "Nessuna squadra nelle vicinanze",
        "pl": "Brak zespołów w pobliżu",
        "ru": "Рядом нет команд",
        "sq": "Nuk ka ekipe afër",
        "zh-Hans": "附近没有队伍",
        "nl": "Geen teams in de buurt",
    },
    "discover_status_no_places_or_teams": {
        "en": "No places or Teams nearby",
        "es": "No hay lugares ni equipos cerca",
        "fr": "Aucun lieu ni équipe à proximité",
        "pt": "Nenhum lugar ou equipe por perto",
        "de": "Keine Orte oder Teams in der Nähe",
        "it": "Nessun luogo o squadra nelle vicinanze",
        "pl": "Brak miejsc i zespołów w pobliżu",
        "ru": "Рядом нет мест или команд",
        "sq": "Nuk ka vende ose ekipe afër",
        "zh-Hans": "附近没有地点或队伍",
        "nl": "Geen plekken of teams in de buurt",
    },
    "discover_empty_teams_nearby": {
        "en": "No Teams nearby",
        "es": "No hay equipos cerca",
        "fr": "Aucune équipe à proximité",
        "pt": "Nenhuma equipe por perto",
        "de": "Keine Teams in der Nähe",
        "it": "Nessuna squadra nelle vicinanze",
        "pl": "Brak zespołów w pobliżu",
        "ru": "Рядом нет команд",
        "sq": "Nuk ka ekipe afër",
        "zh-Hans": "附近没有队伍",
        "nl": "Geen teams in de buurt",
    },
    "discover_empty_places_or_teams_nearby": {
        "en": "No places or Teams nearby",
        "es": "No hay lugares ni equipos cerca",
        "fr": "Aucun lieu ni équipe à proximité",
        "pt": "Nenhum lugar ou equipe por perto",
        "de": "Keine Orte oder Teams in der Nähe",
        "it": "Nessun luogo o squadra nelle vicinanze",
        "pl": "Brak miejsc i zespołów w pobliżu",
        "ru": "Рядом нет мест или команд",
        "sq": "Nuk ka vende ose ekipe afër",
        "zh-Hans": "附近没有地点或队伍",
        "nl": "Geen plekken of teams in de buurt",
    },
    "discover_empty_recovery_places_or_teams": {
        "en": "Try another sport, zoom out, or explore nearby areas.",
        "es": "Prueba otro deporte, aléjate o explora zonas cercanas.",
        "fr": "Essayez un autre sport, dézoomez ou explorez les environs.",
        "pt": "Tente outro esporte, afaste o zoom ou explore áreas próximas.",
        "de": "Probiere eine andere Sportart, zoome heraus oder erkunde die Umgebung.",
        "it": "Prova un altro sport, rimpicciolisci o esplora le zone vicine.",
        "pl": "Spróbuj innej dyscypliny, oddal mapę lub sprawdź okolice.",
        "ru": "Попробуйте другой спорт, уменьшите масштаб или посмотрите соседние районы.",
        "sq": "Provoni një sport tjetër, zmadhoni ose eksploroni zonat afër.",
        "zh-Hans": "试试其他运动、缩小地图，或探索附近区域。",
        "nl": "Probeer een andere sport, zoom uit of verken de omgeving.",
    },
    "discover_team_view_team": {
        "en": "View Team",
        "es": "Ver equipo",
        "fr": "Voir l’équipe",
        "pt": "Ver equipe",
        "de": "Team ansehen",
        "it": "Vedi squadra",
        "pl": "Zobacz zespół",
        "ru": "Открыть команду",
        "sq": "Shiko ekipin",
        "zh-Hans": "查看队伍",
        "nl": "Bekijk team",
    },
    "discover_team_pin_sport_team_format": {
        "en": "%@ Team",
        "es": "Equipo de %@",
        "fr": "Équipe %@",
        "pt": "Equipe de %@",
        "de": "%@-Team",
        "it": "Squadra %@",
        "pl": "Zespół %@",
        "ru": "Команда: %@",
        "sq": "Ekip %@",
        "zh-Hans": "%@ 队伍",
        "nl": "%@-team",
    },
    "discover_team_members_one": {
        "en": "1 member",
        "es": "1 miembro",
        "fr": "1 membre",
        "pt": "1 membro",
        "de": "1 Mitglied",
        "it": "1 membro",
        "pl": "1 członek",
        "ru": "1 участник",
        "sq": "1 anëtar",
        "zh-Hans": "1 名成员",
        "nl": "1 lid",
    },
    "discover_team_members_other_format": {
        "en": "%lld members",
        "es": "%lld miembros",
        "fr": "%lld membres",
        "pt": "%lld membros",
        "de": "%lld Mitglieder",
        "it": "%lld membri",
        "pl": "%lld członków",
        "ru": "%lld участников",
        "sq": "%lld anëtarë",
        "zh-Hans": "%lld 名成员",
        "nl": "%lld leden",
    },
    "discover_team_distance_miles_format": {
        "en": "%.1f mi away",
        "es": "a %.1f mi",
        "fr": "à %.1f mi",
        "pt": "a %.1f mi",
        "de": "%.1f mi entfernt",
        "it": "a %.1f mi",
        "pl": "%.1f mi stąd",
        "ru": "%.1f миль",
        "sq": "%.1f mi larg",
        "zh-Hans": "距离 %.1f 英里",
        "nl": "%.1f mijl verderop",
    },
    "discover_team_preview_dismiss": {
        "en": "Dismiss Team card",
        "es": "Cerrar ficha del equipo",
        "fr": "Fermer la fiche de l’équipe",
        "pt": "Fechar cartão da equipe",
        "de": "Teamkarte schließen",
        "it": "Chiudi scheda squadra",
        "pl": "Zamknij kartę zespołu",
        "ru": "Закрыть карточку команды",
        "sq": "Mbyll kartën e ekipit",
        "zh-Hans": "关闭队伍卡片",
        "nl": "Teamkaart sluiten",
    },
    "discover_team_cluster_a11y_format": {
        "en": "%lld Teams",
        "es": "%lld equipos",
        "fr": "%lld équipes",
        "pt": "%lld equipes",
        "de": "%lld Teams",
        "it": "%lld squadre",
        "pl": "%lld zespołów",
        "ru": "%lld команд",
        "sq": "%lld ekipe",
        "zh-Hans": "%lld 支队伍",
        "nl": "%lld teams",
    },
    "discover_team_cluster_title_format": {
        "en": "%lld Teams",
        "es": "%lld equipos",
        "fr": "%lld équipes",
        "pt": "%lld equipes",
        "de": "%lld Teams",
        "it": "%lld squadre",
        "pl": "%lld zespołów",
        "ru": "%lld команд",
        "sq": "%lld ekipe",
        "zh-Hans": "%lld 支队伍",
        "nl": "%lld teams",
    },
}


def main() -> None:
    data = json.loads(XCSTRINGS.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})
    for key, translations in ENTRIES.items():
        entry = strings.get(key) or {}
        entry["localizations"] = locs(translations)
        strings[key] = entry
    XCSTRINGS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"patched {len(ENTRIES)} keys")


if __name__ == "__main__":
    main()
